kind: pipeline
type: docker
name: Compileer TeX

steps:
  - name: Genereer PDF
    image: texlive:latest
    pull: never
    commands:
      - biber main
      - pdflatex main
    when:
      event: push