kind: pipeline
type: docker
name: Compileer TeX

steps:
  - name: Genereer PDF
    image: texlive:latest
    pull: never
    commands:
      - pdflatex --shell-escape main
      - biber main
      - pdflatex --shell-escape main
    environment:
      USERNAME: root
    when:
      event: push